import os

# -- DEFINIR NOMBRE DE LA BASE DE DATOS --
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_NAME = os.path.join(BASE_DIR, "2_database", "libreria.db")

# -- ESTABLECER DIMENSIONES DE LA VENTANA PRINCIPAL --
VENTANA_ANCHO = 1280
VENTANA_ALTO = 650

# -- CONFIGURAR NUEVA PALETA DE COLORES  --
COLOR_PALIDO_ROSA = "#FFB5E8"
COLOR_PALIDO_MAGENTA = "#FF9CEE"
COLOR_LUMINOSO_LAVANDA = "#FFCCF9"
COLOR_CLARO_AMATISTA = "#FCC2FF"
COLOR_CLARO_LAVANDA = "#F6A6FF"
COLOR_SUAVE_MAGENTA = "#FFA6DB"
COLOR_PALIDO_CARMESI = "#FFA6AE"
COLOR_FONDO_OSCURO = "#1E1E2F"
COLOR_BLANCO = "#FFFFFF"

# -- ASIGNAR COLORES A ROLES EN LA APLICACIÓN --
COLOR_FONDO_PRINCIPAL = COLOR_PALIDO_ROSA
COLOR_CONTENEDORES = COLOR_BLANCO
COLOR_TEXTO = COLOR_FONDO_OSCURO
COLOR_ROSA_FUERTE = COLOR_PALIDO_MAGENTA
COLOR_ROSA_MEDIO = COLOR_SUAVE_MAGENTA
COLOR_ROSA_BOTON_SEC = COLOR_LUMINOSO_LAVANDA
COLOR_BOTON_CRUD = COLOR_CLARO_LAVANDA       
COLOR_BOTON_CATALOGO = COLOR_CLARO_AMATISTA
