-- Sentencias SQL para actualizar autor y editorial de todos los libros:
UPDATE libros SET autor = 'J. C. CERVANTES', editorial = 'Crossbooks México' WHERE titulo = 'LA ETERNIDAD NO ES PARA SIEMPRE';
UPDATE libros SET autor = 'COLLEEN HOOVER', editorial = 'Editorial Planeta' WHERE titulo = '9 DE NOVIEMBRE';
UPDATE libros SET autor = 'ELENA CASTILLO CASTRO', editorial = 'Titania' WHERE titulo = 'A LA SOMBRA DEL ARCOíRIS';
UPDATE libros SET autor = 'A.B. PORANEK', editorial = 'Puck' WHERE titulo = 'LA TRAICIóN DE LOS CISNES';
UPDATE libros SET autor = 'ANSTEY HARRIS', editorial = 'Titania' WHERE titulo = 'ADIóS, PARíS';
UPDATE libros SET autor = 'ROBERT BRYNDZA', editorial = 'SIN INFORMACION' WHERE titulo = 'AGUAS OSCURAS';
UPDATE libros SET autor = 'DISNEY, ALLISON SAFT', editorial = 'Crossbooks México' WHERE titulo = 'ALAS DE ESTRELLA';
UPDATE libros SET autor = 'REBECCA YARROS', editorial = 'Planeta México' WHERE titulo = 'ALAS DE óNIX (EMPíREO 3)';
UPDATE libros SET autor = 'ROGER-POL DROIT', editorial = 'Editorial Ariel' WHERE titulo = 'ALICIA EN EL PAíS DE LAS IDEAS';
UPDATE libros SET autor = 'ÁNGELA BANZAS', editorial = 'Suma' WHERE titulo = 'EL ALIENTO DE LAS LLAMAS / THE BREATH OF FLAMES';
UPDATE libros SET autor = 'KATE GOLDEN', editorial = 'EDICIONES URANO' WHERE titulo = 'AMANECER DE ONYX';
UPDATE libros SET autor = 'SUZANNE COLLINS', editorial = 'MOLINO' WHERE titulo = 'LOS JUEGOS DEL HAMBRE 5 - AMANECER EN LA COSECHA';
UPDATE libros SET autor = 'ÁNGELES QUINTEROS, ÁNGELES VARGAS', editorial = 'Escrito con Tiza' WHERE titulo = 'AMOR ANIMAL';
UPDATE libros SET autor = 'TESSA BAILEY', editorial = 'EDICIONES URANO' WHERE titulo = 'EL AMOR DERRIBA MUROS (LAS REFORMAS DEL AMOR 2)';
UPDATE libros SET autor = 'VALENTINA DE GUZMN Y SMITH', editorial = 'Createspace Independent Publishing Platform' WHERE titulo = 'PRSTAMO HIPOTECARIO';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'ANDA, ANDA, MARI MORENA';
UPDATE libros SET autor = 'EMILY HOUGHTON', editorial = 'Titania' WHERE titulo = 'ANTES DE VERTE';
UPDATE libros SET autor = 'HANNAH NICOLE MAEHRER', editorial = 'Faeris Editorial' WHERE titulo = 'APRENDIZ DEL VILLANO';
UPDATE libros SET autor = 'LYNN PAINTER', editorial = 'SIN INFORMACION' WHERE titulo = 'APUESTO POR NOSOTROS';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'ASALTO MEDICI';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'ASESINA DE DIOSES';
UPDATE libros SET autor = 'HANNAH NICOLE MAEHRER', editorial = 'Faeris Editorial' WHERE titulo = 'ASISTENTE DEL VILLANO';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'ATMOSPHERE';
UPDATE libros SET autor = 'CHRISTINA LAUREN', editorial = 'VR Editoras' WHERE titulo = 'ATRAPADA EN VACACIONES';
UPDATE libros SET autor = 'JOHN PATIENCE', editorial = 'Silver Dolphin en Español' WHERE titulo = 'LA BELLA Y LA BESTIA';
UPDATE libros SET autor = 'JULIO CORTáZAR', editorial = 'ALFAGUARA' WHERE titulo = 'BESTIARIO';
UPDATE libros SET autor = 'CARRIE LEIGHTON', editorial = 'Wonderbooks' WHERE titulo = 'BETTER 1. COLISIóN';
UPDATE libros SET autor = 'HWANG BO-REUM', editorial = 'Planeta México' WHERE titulo = 'BIENVENIDOS A LA LIBRERíA HYUNAM-DONG';
UPDATE libros SET autor = 'DIANE J. WRIGHT', editorial = 'Seedpod Publishing' WHERE titulo = 'BIRTHDAY GIRL';
UPDATE libros SET autor = 'ANDREA LONGARELA', editorial = 'Planeta Publishing' WHERE titulo = 'CUANDO DESPIERTEN LAS FLORES (NOVELA) / WHEN THE FLOWERS BLOOM AGAIN (A NOVEL)';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'BLUEBELLS';
UPDATE libros SET autor = 'ALLISON LEIGH', editorial = 'Silhouette' WHERE titulo = 'THE BOSS''S CHRISTMAS PROPOSAL';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'BUTCHER';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'BUTCHER AND BLACKBIRD';
UPDATE libros SET autor = 'FRANCISCA SOLAR', editorial = 'EDICIONES URANO' WHERE titulo = 'EL BUZóN DE LAS IMPURAS';
UPDATE libros SET autor = 'KARINE BERNAL LOBO', editorial = 'SIN INFORMACION' WHERE titulo = 'LAS CADENAS DEL REY';
UPDATE libros SET autor = 'BRAIDEE OTTO', editorial = 'VR Europa' WHERE titulo = 'CANTO DE TORMENTOS';
UPDATE libros SET autor = 'SARAH RIVENS', editorial = 'Ediciones Martínez Roca' WHERE titulo = 'CAPTIVE: NO JUEGUES CONMIGO';
UPDATE libros SET autor = 'EMILY J. TAYLOR', editorial = 'EDICIONES URANO' WHERE titulo = 'CARTAS DE OTRO MUNDO';
UPDATE libros SET autor = 'ROALD DAHL', editorial = 'ALFAGUARA IJC' WHERE titulo = 'CHARLIE Y EL GRAN ASCENSOR DE CRISTAL (COLECCIóN ALFAGUARA CLáSICOS)';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'CIUDAD DE POLVO DE ESTRELLAS';
UPDATE libros SET autor = 'FRANCISCA SOLAR', editorial = 'SIN INFORMACION' WHERE titulo = 'LOS úLTIMOS DíAS DE CLAYTON  CO';
UPDATE libros SET autor = 'BAL KHABRA', editorial = 'VR Europa' WHERE titulo = 'COLLIDE';
UPDATE libros SET autor = 'SAINT AUGUSTINE (OF HIPPO)', editorial = 'SIN INFORMACION' WHERE titulo = 'CONFESIONES';
UPDATE libros SET autor = 'MARíA MARTíNEZ', editorial = 'SIN INFORMACION' WHERE titulo = 'CORAZóN ROTO';
UPDATE libros SET autor = 'H. HUNTING', editorial = 'Wonderbooks' WHERE titulo = 'CORAZóN AGRIDULCE';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'CORRUPT';
UPDATE libros SET autor = 'LYLA SAGE', editorial = 'EDICIONES URANO' WHERE titulo = 'CORTAR EL VIENTO';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'Publicatuslibros.com' WHERE titulo = 'CRUCIGRAMA DE AMAPOLAS';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'CRUZAR LA LíNEA';
UPDATE libros SET autor = 'ANDREA LONGARELA', editorial = 'SIN INFORMACION' WHERE titulo = 'CUANDO DESPIERTEN LAS FLORES';
UPDATE libros SET autor = 'NEREA PASCUAL', editorial = 'Esencia' WHERE titulo = 'CUANDO EL CIELO SE VUELVA AMARILLO';
UPDATE libros SET autor = 'DUSTIN THAO', editorial = 'Ediciones Kiwi' WHERE titulo = 'CUANDO HARU ESTUVO AQUí';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'CUANDO NO QUEDEN MáS ESTRELLAS QUE CONTAR';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'CUANDO SEAS MíA';
UPDATE libros SET autor = 'NAVESSA ALLEN', editorial = 'Ediciones B' WHERE titulo = 'DE RODILLAS / CAUGHT UP';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'DE SANGRE Y CENIZAS';
UPDATE libros SET autor = 'ALI HAZELWOOD', editorial = 'Contraluz Editorial' WHERE titulo = 'DEL ODIO AL AMOR';
UPDATE libros SET autor = 'SHEA ERNSHAW', editorial = 'SIN INFORMACION' WHERE titulo = 'UN DELIRIO ENCANTADOR';
UPDATE libros SET autor = 'TAYLOR HUTTON', editorial = 'EDICIONES URANO' WHERE titulo = 'DESEOS PELIGROSOS';
UPDATE libros SET autor = 'BELEN MARTINEZ', editorial = 'Ediciones Urano' WHERE titulo = 'DESPUéS DEL OCéANO';
UPDATE libros SET autor = 'VICTORIA AVEYARD', editorial = 'Océano Gran Travesía' WHERE titulo = 'DESTRUCTORA DE DESTINOS';
UPDATE libros SET autor = 'MAR PETRYK', editorial = 'Planeta Argentina' WHERE titulo = 'DETONANTE';
UPDATE libros SET autor = 'SHANA FESTE, JEN BESSER', editorial = 'Editorial Planeta' WHERE titulo = 'DIANA IN LOVE';
UPDATE libros SET autor = 'SILVIA MORENO-GARCíA', editorial = 'Minotauro' WHERE titulo = 'DIOSES DE JADE Y SOMBRA';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'DIOSES INDOMABLES (WICKED BEAUTY)';
UPDATE libros SET autor = 'CHARLENE DIANE MITCHELL', editorial = 'Xlibris Corporation' WHERE titulo = 'DIRTY DIANA';
UPDATE libros SET autor = 'A.B. PORANEK', editorial = 'Puck' WHERE titulo = 'DONDE MORA LA OSCURIDAD';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'DOS VIDAS PARA CRECER';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'DULCE PESADILLA';
UPDATE libros SET autor = 'CHRISTINA LAUREN', editorial = 'VR Europa' WHERE titulo = 'LA ECUACIóN DE LAS ALMAS GEMELAS';
UPDATE libros SET autor = 'TESSA BAILEY', editorial = 'EDICIONES URANO' WHERE titulo = 'EL AMOR NO TIENE REGLAS';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'EL AMOR Y LOS CLICHéS';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'EL ARTE DE AHOGARSE';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'EL ARTE DE SER NOSOTROS';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'EL AñO DE LA LANGOSTA';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'EL CANTO DE LOS AHOGADOS';
UPDATE libros SET autor = 'ANDREA LONGARELA', editorial = 'Crossbooks' WHERE titulo = 'EL COLOR DE LAS COSAS INVISIBLES';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'EL CONVENTO';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'EL CORAZóN DEL REY';
UPDATE libros SET autor = 'ALICE KELLEN', editorial = 'Titania' WHERE titulo = 'EL DíA QUE DEJó DE NEVAR EN ALASKA';
UPDATE libros SET autor = 'ANDREA LONGARELA', editorial = 'Crossbooks' WHERE titulo = 'EL FARO DE LOS AMORES DORMIDOS';
UPDATE libros SET autor = 'REBECCA ROBINSON', editorial = 'Ediciones Martínez Roca' WHERE titulo = 'EL LOBO Y LA SERPIENTE';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'EL MAGO DE OZ';
UPDATE libros SET autor = 'KIM JIYUN', editorial = 'Editorial Planeta' WHERE titulo = 'EL MISTERIO DE LA LAVANDERíA DE YEONNAM-DONG';
UPDATE libros SET autor = 'CARISSA BROADBENT', editorial = 'Editorial Planeta' WHERE titulo = 'EL PáJARO Y EL CORAZóN DE PIEDRA';
UPDATE libros SET autor = 'C.S. PACAT', editorial = 'EDICIONES URANO' WHERE titulo = 'EL PRíNCIPE CAUTIVO: EL ESCLAVO';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'Contraluz' WHERE titulo = 'EL PROBLEMA DEL PARAíSO (THE PARADISE PROBLEM)';
UPDATE libros SET autor = 'HOLLY JACKSON', editorial = 'Crossbooks' WHERE titulo = 'EL RETORNO DE RACHEL PRICE';
UPDATE libros SET autor = 'JAVIERA VALENZUELA', editorial = 'Crossbooks Chile' WHERE titulo = 'EL REY DE LA MáSCARA OSCURA';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'EL SECRETO DE LAS NUBES';
UPDATE libros SET autor = 'ANGELA CERVANTES', editorial = 'Henry Holt and Company (BYR)' WHERE titulo = 'EL MISTERIO DE LA COPA DEL MUNDO ROBADA';
UPDATE libros SET autor = 'LYNN PAINTER', editorial = 'EDICIONES URANO' WHERE titulo = 'EL SEñOR NúMERO DESCONOCIDO';
UPDATE libros SET autor = 'NICOLA YOON', editorial = 'SIN INFORMACION' WHERE titulo = 'EL SOL TAMBIéN ES UNA ESTRELLA';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'EL SUSURRO DE LAS ESTRELLAS';
UPDATE libros SET autor = 'BELéN MARTíNEZ', editorial = 'SIN INFORMACION' WHERE titulo = 'EL VALS DE LA BRUJA';
UPDATE libros SET autor = 'PäR LAGERKVIST', editorial = 'Andres Bello' WHERE titulo = 'EL VERDUGO';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'EN LAS NUBES';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'EN LO MáS PROFUNDO';
UPDATE libros SET autor = ',', editorial = 'EDICIONES URANO' WHERE titulo = 'UN ENCANTAMIENTO FRáGIL';
UPDATE libros SET autor = 'NORA ROBERTS', editorial = 'Harlequin, una división de HarperCollins Ibérica' WHERE titulo = 'ENTRE Tú Y YO';
UPDATE libros SET autor = 'GILRAEN EäRFALAS', editorial = 'Planeta México' WHERE titulo = 'ERES EL AMOR DE MI OTRA VIDA';
UPDATE libros SET autor = 'CAT SCHIELD', editorial = 'Harlequin, una división de HarperCollins Ibérica' WHERE titulo = 'ESCáNDALO REAL';
UPDATE libros SET autor = 'TESSA BAILEY', editorial = 'EDICIONES URANO' WHERE titulo = 'UN ESCAPARATE NAVIDEñO';
UPDATE libros SET autor = 'ELíSABET BENAVENT', editorial = 'SUMA' WHERE titulo = 'ESNOB';
UPDATE libros SET autor = 'EDUARDO ORDóñEZ', editorial = 'SIN INFORMACION' WHERE titulo = 'ANIMAL ETéREO';
UPDATE libros SET autor = 'LAUREN ROBERTS', editorial = 'Alfaguara' WHERE titulo = 'FEARFUL. UNA HISTORIA DE POWERLESS / FEARFUL. A POWERLESS STORY';
UPDATE libros SET autor = 'LYNN PAINTER', editorial = 'EDICIONES URANO' WHERE titulo = 'FELICES PARA NUNCA';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'FINGE QUE ME QUIERES';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'THE FIVE BROTHERS';
UPDATE libros SET autor = 'ELSIE SILVER', editorial = 'Contraluz Editorial' WHERE titulo = 'FLAWLESS: SIN REGLAS';
UPDATE libros SET autor = 'MARíA MARTíNEZ', editorial = 'Crossbooks' WHERE titulo = 'LA FRAGILIDAD DE UN CORAZóN BAJO LA LLUVIA';
UPDATE libros SET autor = 'MAXIMILIANO MATAYOSHI', editorial = 'Odelia editora' WHERE titulo = 'GAIJIN';
UPDATE libros SET autor = 'EMILY HENRY', editorial = 'Editorial Planeta' WHERE titulo = 'GENTE QUE CONOCEMOS EN VACACIONES';
UPDATE libros SET autor = 'CHERRY CHIC', editorial = 'Editorial Planeta' WHERE titulo = 'GIULIA, EL AMOR Y UN PUñADO DE LAVANDA';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'GRIMM MORTAL';
UPDATE libros SET autor = 'MARIO ESCOBAR', editorial = 'EDICIONES B' WHERE titulo = 'LA GUARDIANA DE LIBROS';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'GUARDIANES. LOS CONDENADOS';
UPDATE libros SET autor = 'SARAH HAWLEY', editorial = 'Titania' WHERE titulo = 'GUíA DE BRUJAS PARA CITAS FALSAS CON UN DEMONIO';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMacion' WHERE titulo = 'HAS LLAMADO A SAM';
UPDATE libros SET autor = 'SARAH A. PARKER', editorial = 'PLAZA  JANÉS' WHERE titulo = 'HASTA QUE CAIGA LA LUNA (LA CAíDA LUNAR 1)';
UPDATE libros SET autor = 'INMA RUBIALES', editorial = 'Editorial Planeta' WHERE titulo = 'HASTA QUE NOS QUEDEMOS SIN ESTRELLAS';
UPDATE libros SET autor = 'KATHRYN PURDIE', editorial = 'EDICIONES URANO' WHERE titulo = 'HECHICERA DE HUESOS. EL AMANECER';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'HIDEAWAY';
UPDATE libros SET autor = 'PARICIA. IBRCENA', editorial = 'SIN INFORMACION' WHERE titulo = 'HIJOS DORADOS/ GOLDEN CHILDREN.';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'LA HIPóTESIS DEL AMOR';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'HOY SE LO DIGO';
UPDATE libros SET autor = 'COLLEEN HOOVER', editorial = 'Editorial Planeta' WHERE titulo = 'HUNDIDA';
UPDATE libros SET autor = 'THOMAS BERNHARD', editorial = 'Alianza Editorial' WHERE titulo = 'LA CALERA';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'INVOCACIóN';
UPDATE libros SET autor = 'RAFAEL CANOMANUEL', editorial = 'LibrosEnRed' WHERE titulo = 'GODS - LA ISLA DE LOS DIOSES';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'LA ISLA DE LOS ANHELOS';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'JOSH Y HAZEL: GUíA PARA EL FRACASO AMOROSO';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'JUEGO DE DOS';
UPDATE libros SET autor = 'KATHARINE MCGEE', editorial = 'EDICIONES URANO' WHERE titulo = 'JUEGO DE REINAS';
UPDATE libros SET autor = 'ANDREA LONGARELA', editorial = 'Crossbooks' WHERE titulo = 'JULIETTE Y LAS CANCIONES PERDIDAS';
UPDATE libros SET autor = 'ISABEL IBAñEZ', editorial = 'EDICIONES URANO' WHERE titulo = 'JUNTOS EN LA HOGUERA';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'KILLSWITCH';
UPDATE libros SET autor = 'MELISSA BLAIR', editorial = 'Planeta Colombia' WHERE titulo = 'LA ASESINA DEL REY';
UPDATE libros SET autor = 'ANNE GRIFFIN', editorial = 'EDICIONES URANO' WHERE titulo = 'LA CHICA QUE OíA A LOS MUERTOS';
UPDATE libros SET autor = 'ISABELLE COUDRIER', editorial = 'Lumen Editorial' WHERE titulo = 'LA ECUACIN DEL AMOR / LOVE EQUATION';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'LA FAN NúMERO 1';
UPDATE libros SET autor = 'KATE MORTON', editorial = 'SUMA' WHERE titulo = 'LA HIJA DEL RELOJERO';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'LA HORA AZUL';
UPDATE libros SET autor = 'GEORGIA SUMMERS', editorial = 'Umbriel' WHERE titulo = 'LA LIBRERíA DE LADY DESTINO';
UPDATE libros SET autor = 'SAWAKO NATORI', editorial = 'Espasa' WHERE titulo = 'LA LIBRERíA DE LOS VIERNES';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'LA MAGIA DE LAS CASUALIDADES';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'LA MALDICIóN DE LA SANGRE';
UPDATE libros SET autor = 'RAMESH NATHAN', editorial = 'Babelcube Inc.' WHERE titulo = 'LA MECáNICA DEL ALMA';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'LA NIñA SALVAJE';
UPDATE libros SET autor = 'CATHARINA MAURA', editorial = 'Espasa México' WHERE titulo = 'LA NOVIA EQUIVOCADA';
UPDATE libros SET autor = 'DAWN BROWER', editorial = 'Babelcube Inc.' WHERE titulo = 'LA PRINCESA ENCANTADA';
UPDATE libros SET autor = 'ALI HAZELWOOD', editorial = 'Contraluz Editorial' WHERE titulo = 'LA QUíMICA DEL AMOR';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'LA SONRISA DEL DEMONIO';
UPDATE libros SET autor = 'ALI HAZELWOOD', editorial = 'Contraluz Editorial' WHERE titulo = 'LA TEORíA DEL AMOR';
UPDATE libros SET autor = 'LUIS CORNEJO, LUIS CORNEJO GAMBOA', editorial = 'SIN INFORMACION' WHERE titulo = 'LA TORMENTA';
UPDATE libros SET autor = 'PEDRO RUIZ', editorial = 'Planeta Publishing Corporation' WHERE titulo = 'LA úLTIMA CARTA';
UPDATE libros SET autor = 'DONNA BARBA HIGUERA', editorial = 'Chronicle Books' WHERE titulo = 'LA úLTIMA CUENTISTA';
UPDATE libros SET autor = 'BLUE JEANS', editorial = 'Editorial Planeta' WHERE titulo = 'LA úLTIMA VEZ QUE PIENSO EN TI';
UPDATE libros SET autor = 'EMIL PFUNDHELLER', editorial = 'SIN INFORMACION' WHERE titulo = 'ON THE CHARACTER OF LADY MACBETH';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'LARGA VIDA AL REY';
UPDATE libros SET autor = 'CARISSA BROADBENT', editorial = 'Planeta Publishing' WHERE titulo = 'LAS CENIZAS Y EL REY MALDITO / THE ASHES AND THE STAR-CURSED KING (LAS CORONAS DE NYAXIA 2)';
UPDATE libros SET autor = 'REBECCA YARROS', editorial = 'Planeta México' WHERE titulo = 'LAS COSAS MáS PRECIOSAS';
UPDATE libros SET autor = 'COCO MELLORS', editorial = 'EDICIONES URANO' WHERE titulo = 'LAS HERMANAS BLUE';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'LAS SIRENAS';
UPDATE libros SET autor = 'AVA STRONG', editorial = 'Ava Strong' WHERE titulo = 'LA PRIMERA CHICA (UNA NOVELA DE SUSPENSE DE LAYLA CAINE - LIBRO 3)';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'LECTURA DE VERANO';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'LLéVAME A CUALQUIER LUGAR';
UPDATE libros SET autor = 'MARíA MARTíNEZ', editorial = 'Crossbooks' WHERE titulo = 'LO QUE LA NIEVE SUSURRA AL CAER';
UPDATE libros SET autor = 'MIGUEL FERRADA', editorial = 'Stefano Books Chile' WHERE titulo = 'LOS BRUJOS DEL FIN DEL MUNDO';
UPDATE libros SET autor = 'TAYLOR JENKINS REID', editorial = 'SIN INFORMACION' WHERE titulo = 'LOS DOS AMORES DE MI VIDA';
UPDATE libros SET autor = 'SUZANNE COLLINS', editorial = 'Molino' WHERE titulo = 'LOS JUEGOS DEL HAMBRE 1 - LOS JUEGOS DEL HAMBRE';
UPDATE libros SET autor = 'TAYLOR JENKINS REID', editorial = 'Urano' WHERE titulo = 'LOS SIETE MARIDOS DE EVELYN HUGO';
UPDATE libros SET autor = 'FRANCISCA SOLAR', editorial = 'Stefano Books' WHERE titulo = 'LOS úLTIMOS DíAS DE CLAYTON AND CO.';
UPDATE libros SET autor = 'GUSTAVE FLAUBERT', editorial = 'SIN INFORMACION' WHERE titulo = 'MADAME BOVARY';
UPDATE libros SET autor = 'IVY PEMBROKE', editorial = 'Titania' WHERE titulo = 'MAGIA EN LA CALLE NAVIDAD';
UPDATE libros SET autor = 'LUIS ZUECO', editorial = 'EDICIONES B' WHERE titulo = 'EL MAPA DE UN MUNDO NUEVO';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'MARI, NO VEAS ESTO';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'MáS QUE UNA POSIBILIDAD';
UPDATE libros SET autor = 'FRANCESCA ZAPPIA', editorial = 'EDICIONES URANO' WHERE titulo = 'MáSCARA DE GATO';
UPDATE libros SET autor = 'MONA KASTEN', editorial = 'Editorial Planeta' WHERE titulo = 'SAVE ME (SERIE MAXTON HALL 1)';
UPDATE libros SET autor = 'LARRY DRELLER', editorial = 'EDAF' WHERE titulo = 'USTED PUEDE SER MEDIUM';
UPDATE libros SET autor = 'LYNN PAINTER', editorial = 'EDICIONES URANO' WHERE titulo = 'MEJOR QUE EN LAS PELíCULAS';
UPDATE libros SET autor = 'ALYSON RICHMAN', editorial = 'Planeta Publishing' WHERE titulo = 'LA MELODíA DE LA MEMORIA';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'MENTIRAS A DOBLE FILO';
UPDATE libros SET autor = 'CASEY MCQUISTON', editorial = 'MOLINO' WHERE titulo = 'MENú PARA DOS';
UPDATE libros SET autor = 'CARMEN RUIZ', editorial = 'HarperCollins Ibérica' WHERE titulo = 'BAILANDO EN LA TEMPESTAD';
UPDATE libros SET autor = 'ISABEL. ALLENDE', editorial = 'Vintage Espanol' WHERE titulo = 'MI NOMBRE ES EMILIA DEL VALLE / MY NAME IS EMILIA DEL VALLE';
UPDATE libros SET autor = 'ALEXANDRA MOODY', editorial = 'ALFAGUARA IJC' WHERE titulo = 'MI QUERIDO RIVAL';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'MIL RECUERDOS TUYOS';
UPDATE libros SET autor = 'MICHIKO AOYAMA', editorial = 'Editorial Planeta' WHERE titulo = 'MIS LUNES CON AROMA A MATCHA';
UPDATE libros SET autor = 'LYNN PAINTER', editorial = 'EDICIONES URANO' WHERE titulo = 'NADA COMO EN LAS PELíCULAS';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'NADA DE ESTO ES VERDAD';
UPDATE libros SET autor = 'MEGAN MAXWELL', editorial = 'Esencia' WHERE titulo = 'UNA NAVIDAD MUY FUN, FUN, FUN';
UPDATE libros SET autor = 'RACHEL LYNN SOLOMON', editorial = 'SIN INFORMACION' WHERE titulo = 'NEGOCIOS O PLACER';
UPDATE libros SET autor = 'KAZUO ISHIGURO', editorial = 'Vintage' WHERE titulo = 'NOCTURNES';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'NIGHTSHADE';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'NO CONFíES EN ASHER HALL';
UPDATE libros SET autor = 'VI KEELAND', editorial = 'Chic Editorial' WHERE titulo = 'NO DEBERíAMOS';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'NO DEBíA SER ASí';
UPDATE libros SET autor = 'MARIO GUERRA', editorial = 'AGUILAR' WHERE titulo = 'ESTO NO ES AMOR';
UPDATE libros SET autor = 'ALISON ESPACH', editorial = 'VR Europa' WHERE titulo = 'NO ESTáS EN LA LISTA';
UPDATE libros SET autor = 'ALEXENE FAROL FOLLMUTH', editorial = 'EDICIONES URANO' WHERE titulo = 'NOCHE DE CABALLEROS';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'NOSOTROS EN LA LUNA';
UPDATE libros SET autor = 'WILLIAM S. BURROUGHS', editorial = 'SIN INFORMACION' WHERE titulo = 'EXPRESO NOVA';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'NUESTRA DESQUICIADA HISTORIA DE AMOR';
UPDATE libros SET autor = 'MEGAN MAXWELL', editorial = 'SIN INFORMACION' WHERE titulo = 'NUESTRO LARGO ADIóS';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'NUESTRO LUGAR EN EL MUNDO';
UPDATE libros SET autor = 'CARMEN ARANDA', editorial = 'SIN INFORMACION' WHERE titulo = 'NUEVO ENGAñO';
UPDATE libros SET autor = 'NICHOLAS SPARKS, M. NIGHT SHYAMALAN', editorial = 'ROCA EDITORIAL' WHERE titulo = 'NUNCA OLVIDES QUE TE QUIERO';
UPDATE libros SET autor = 'ANDREA LONGARELA', editorial = 'Esencia' WHERE titulo = 'OJALá ESTA FUERA NUESTRA HISTORIA DE AMOR';
UPDATE libros SET autor = 'JULIA DE LA FUENTE MIGALLóN', editorial = 'EDICIONES URANO' WHERE titulo = 'OYE, DIABLA';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'PABELLóN 57';
UPDATE libros SET autor = 'MALENA HEHN', editorial = 'VRYA' WHERE titulo = 'UN PACTO ELECTRIZANTE';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'PECADOR';
UPDATE libros SET autor = 'WILLIAM HAND BROWNE', editorial = 'SIN INFORMACION' WHERE titulo = 'THE SOUTHERN MAGAZINE';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'PESADILLA EN NAVIDAD';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'PRIMER AMOR';
UPDATE libros SET autor = 'CHRISTINE FEEHAN', editorial = 'Titania' WHERE titulo = 'PROMESAS OSCURAS';
UPDATE libros SET autor = 'EMILY RATH', editorial = 'Planeta Publishing' WHERE titulo = 'PUCKING AROUND. EL AMOR NO ES COSA DE DOS';
UPDATE libros SET autor = 'V. E. SCHWAB', editorial = 'Umbriel' WHERE titulo = 'QUE ENTIERREN NUESTROS HUESOS EN LA MEDIANOCHE';
UPDATE libros SET autor = 'ALICE KELLEN', editorial = 'Planeta Publishing' WHERE titulo = 'QUEDARá EL AMOR (NOVELA) / LOVE WILL REMAIN (A NOVEL)';
UPDATE libros SET autor = 'PENELOPE WARD', editorial = 'Titania' WHERE titulo = 'QUERIDO VECINO';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'QUIZáS EN OTRA VIDA';
UPDATE libros SET autor = 'MARTA SANTÉS', editorial = 'Titania' WHERE titulo = 'RECUéRDAME, ALICE';
UPDATE libros SET autor = 'CARMEN ROMERO LORENZO', editorial = 'EDICIONES URANO' WHERE titulo = 'REINA DEL ESTíO';
UPDATE libros SET autor = 'ANA HUANG', editorial = 'Crossbooks' WHERE titulo = 'PECADOS 3. REY DE LA CODICIA';
UPDATE libros SET autor = 'ANA HUANG', editorial = 'Crossbooks' WHERE titulo = 'PECADOS 4. REY DE LA DESIDIA';
UPDATE libros SET autor = 'ANA HUANG', editorial = 'Crossbooks' WHERE titulo = 'PECADOS 1. REY DE LA IRA';
UPDATE libros SET autor = 'ANA HUANG', editorial = 'SIN INFORMACION' WHERE titulo = 'PECADOS 2. REY DE LA SOBERBIA';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'ROMPER EL CíRCULO';
UPDATE libros SET autor = 'REBECCA ZANETTI', editorial = 'EDICIONES URANO' WHERE titulo = 'UNA ROSA MALDITA';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'ROSE IN CHAINS';
UPDATE libros SET autor = 'MEAGAN BRANDY', editorial = 'Ediciones Martínez Roca' WHERE titulo = 'SAY YOU SWEAR (JúRAMELO)';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'SECRETO';
UPDATE libros SET autor = 'MARIE BENEDICT', editorial = 'Planeta México' WHERE titulo = 'EL SECRETO DE SU MENTE';
UPDATE libros SET autor = 'BRUNO PUELLES', editorial = 'EDICIONES URANO' WHERE titulo = 'LOS SECRETOS DEL HOTEL JARDíN DE ODETTE';
UPDATE libros SET autor = 'ELIZABETH LIM', editorial = 'Destino Argentina' WHERE titulo = 'SEIS GRULLAS';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'SEIS LITROS PROMEDIO';
UPDATE libros SET autor = 'CARISSA BROADBENT', editorial = 'Planeta México' WHERE titulo = 'LA SERPIENTE Y LAS ALAS DE LA NOCHE (EDICIóN MEXICANA)';
UPDATE libros SET autor = 'EMMA GIL', editorial = 'Ediciones Martínez Roca' WHERE titulo = 'SI FUéRAMOS ETERNOS';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'THE BUILDING OF THE "CIBOLA"';
UPDATE libros SET autor = 'MADELINE BAKER', editorial = 'Harlequin, una división de HarperCollins Ibérica' WHERE titulo = 'SIEMPRE FUISTE Tú';
UPDATE libros SET autor = 'BUDD HOPKINS, CAROL RAINEY', editorial = 'Simon and Schuster' WHERE titulo = 'SIGHT UNSEEN';
UPDATE libros SET autor = 'BELéN MARTíNEZ', editorial = 'SIN INFORMACION' WHERE titulo = 'UNA SONATA DE VERANO';
UPDATE libros SET autor = 'MARíA REIG, MARíA REIG ALONSO', editorial = 'SIN INFORMACION' WHERE titulo = 'SONó UN VIOLíN EN PARíS';
UPDATE libros SET autor = 'BAL KHABRA', editorial = 'Vera Romantica' WHERE titulo = 'SPIRAL';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'TE ODIO CON AMOR';
UPDATE libros SET autor = 'SYOU ISHIDA', editorial = 'Planeta Publishing' WHERE titulo = 'TE RECETO UN GATO: EL BESTSELLER JAPONéS QUE HA ENGATUSADO A LECTORES EN TODO EL MUNDO / WE''LL PRESCRIBE YOU A CAT';
UPDATE libros SET autor = 'JAY SANDOVAL', editorial = 'Crossbooks Perú' WHERE titulo = 'LA TEORíA DE KIM II';
UPDATE libros SET autor = 'ANA PéREZ', editorial = 'MONTENA' WHERE titulo = 'TERAPIA PARA LLEVAR';
UPDATE libros SET autor = 'ANA HUANG', editorial = 'Thorndike Press Large Print' WHERE titulo = 'THE DEFENDER';
UPDATE libros SET autor = 'SIN INFORMACION', editorial = 'SIN INFORMACION' WHERE titulo = 'THE LUCKY ONES: FAMA, RUMORES Y DEMáS';
UPDATE libros SET autor = 'IDUN A.I. SAAGE', editorial = 'BookRix' WHERE titulo = 'THE STRIKER''S FINISHING GUIDE: SCORE MORE GOALS WITH PRECISION  POWER';
UPDATE libros SET autor = 'TREVIN WAX', editorial = 'BH Publishing Group' WHERE titulo = 'THIS IS OUR TIME';
UPDATE libros SET autor = 'MELISSA WIESNER', editorial = 'EDICIONES URANO' WHERE titulo = 'TODOS NUESTROS RECUERDOS';
UPDATE libros SET autor = 'LISA JEWELL', editorial = 'Crossbooks Chile' WHERE titulo = 'TRAS LA NOCHE. UNA NOVELA DE JESSICA JONES';