-- Sentencias SQL para actualizar la base de datos:
UPDATE libros SET genero = 'Romantasy' WHERE titulo = 'EL CANTO DE LOS AHOGADOS';
UPDATE libros SET genero = 'Romantasy' WHERE titulo = 'ASISTENTE DEL VILLANO';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'CANTO DE TORMENTOS';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'UNA PUERTA EN LA SOMBRA';
UPDATE libros SET genero = 'Romantasy' WHERE titulo = 'MENTIRAS A DOBLE FILO';
UPDATE libros SET genero = 'Romantasy' WHERE titulo = 'ROSE IN CHAINS';
UPDATE libros SET genero = 'Romantasy' WHERE titulo = 'EL TRONO DE LOS CAíDOS';
UPDATE libros SET genero = 'Romantasy' WHERE titulo = 'LAS CADENAS DEL REY';
UPDATE libros SET genero = 'Romantasy' WHERE titulo = 'DE SANGRE Y CENIZAS';
UPDATE libros SET genero = 'Romantasy' WHERE titulo = 'GUíA DE BRUJAS PARA CITAS FALSAS CON UN DEMONIO';
UPDATE libros SET genero = 'Romantasy' WHERE titulo = 'UN ENCANTAMIENTO FRáGIL';
UPDATE libros SET genero = 'Romantasy' WHERE titulo = 'AMANECER DE ONYX';
UPDATE libros SET genero = 'Romantasy' WHERE titulo = 'PROMESAS OSCURAS';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'LA SEGUNDA MUERTE DE LOCKE';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'LA TRAICIóN DE LOS CISNES';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'LA LIBRERíA DE LADY DESTINO';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'REINA DEL ESTíO';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'CARTAS DE OTRO MUNDO';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'LAS SIRENAS';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'ASESINA DE DIOSES';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'ASALTO MEDICI';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'EL VALS DE LA BRUJA';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'DONDE MORA LA OSCURIDAD';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'LA MALDICIóN DE LA SANGRE';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'DESPUéS DEL OCéANO';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'EL TRONO DEL PRISIONERO';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'EL ARTE DE AHOGARSE';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'MáSCARA DE GATO';
UPDATE libros SET genero = 'Romantasy' WHERE titulo = 'EL LOBO Y LA SERPIENTE';
UPDATE libros SET genero = 'Romantasy' WHERE titulo = 'LA PRINCESA ENCANTADA';
UPDATE libros SET genero = 'Romantasy' WHERE titulo = 'UNA CORTE DE ROSAS Y ESPINAS';
UPDATE libros SET genero = 'Romantasy' WHERE titulo = 'DULCE PESADILLA';
UPDATE libros SET genero = 'Romantasy' WHERE titulo = 'LA ASESINA DEL REY';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'ALAS DE ESTRELLA';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'SEIS GRULLAS';
UPDATE libros SET genero = 'Fantasía' WHERE titulo = 'BIENVENIDOS A LA LIBRERíA HYUNAM-DONG';