[theme]
# Color de acento para botones y elementos interactivos:
# Usaremos el "Pastel Violet" que es vibrante y elegante.
primaryColor = "#C994C0"

# Color de fondo principal:
# Como pediste, usamos blanco puro para máxima claridad.
backgroundColor = "#FFFFFF"

# Color de fondo secundario (barra lateral, expanders, tablas):
# El "Periwinkle Grey" es perfecto para un contraste suave.
secondaryBackgroundColor = "#FFC5D3"

# Color del texto:
# El "Dusky Blue" es oscuro, con carácter y garantiza una legibilidad perfecta.
textColor = "#5B5E93"

# Tipografía:
font = "Lato"